github: build-gluon: always run build-complete dummy job
Apparently skipped jobs count as successful in regargs to required status checks.

So there needs to be an explicit failure.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -258,9 +258,16 @@ jobs:
     name: All Targets Build
     runs-on: ubuntu-22.04
     needs: [build, build-meta, targets]
+    if: ${{ always() }}
     steps:
-      - run: |
-          echo "All builds succeded"
+      - name: Error out if there is a failure
+        if: ${{ needs.build_firmware.result != 'success' }}
+        run: |
+          echo "One or more builds failed."
+          exit 1
+      - name: Proceed if all passed
+        if: ${{ needs.build_firmware.result == 'success' }}
+        run: echo "All required builds succeded!"
 
   manifest:
     needs: [build, build-meta, targets]
